"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](surface0)\
$os\
$username\
[](bg:surface1 fg:surface0)\
$directory\
[](fg:surface1 bg:overlay0)\
$git_branch\
$git_status\
[](fg:overlay0 bg:overlay1)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:overlay1 bg:overlay2)\
$docker_context\
[ ](fg:overlay2)\
$line_break$character"""

# This puts the time on the far right side of the prompt
right_format = """
$time
"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
style = "bg:surface0 fg:text"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:surface0 fg:text"
style_root = "bg:surface0 fg:peach"
format = '[ $user ]($style)'

[directory]
style = "fg:peach bg:surface1"
truncation_length = 3
truncation_symbol = "…/"
format = "[ $path ]($style)"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:overlay0 fg:text"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "bg:overlay0 fg:subtext0"
format = "[$all_status$ahead_behind ]($style)"

[nodejs]
symbol = ""
style = "bg:overlay1 fg:green"
format = "[ $symbol( $version) ]($style)"

[c]
symbol = " "
style = "bg:overlay1 fg:sky"
format = "[ $symbol( $version) ]($style)"

[rust]
symbol = ""
style = "bg:overlay1 fg:peach"
format = "[ $symbol( $version) ]($style)"

[golang]
symbol = ""
style = "bg:overlay1 fg:teal"
format = "[ $symbol( $version) ]($style)"

[php]
symbol = ""
style = "bg:overlay1 fg:mauve"
format = "[ $symbol( $version) ]($style)"

[java]
symbol = " "
style = "bg:overlay1 fg:red"
format = "[ $symbol( $version) ]($style)"

[kotlin]
symbol = ""
style = "bg:overlay1 fg:pink"
format = "[ $symbol( $version) ]($style)"

[haskell]
symbol = ""
style = "bg:overlay1 fg:yellow"
format = "[ $symbol( $version) ]($style)"

[python]
symbol = ""
style = "bg:overlay1 fg:sapphire"
format = "[ $symbol( $version) ]($style)"

[docker_context]
symbol = ""
style = "bg:overlay2 fg:sky"
format = "[ $symbol( $context) ]($style)"

[time]
disabled = false
time_format = "%R"
style = "fg:lavender"
format = "[ $time]($style)"

[line_break]

[character]
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:peach)'
vimcmd_replace_symbol = '[](bold fg:maroon)'
vimcmd_visual_symbol = '[](bold fg:lavender)'
